######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 20 19:05:02 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keythread.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += keythread.cpp main.cpp mainwindow.cpp
